name: 'Save Angular Cache'
description: 'Save Angular build cache after build or test'
runs:
  using: 'composite'
  steps:
    - name: Save Angular Cache
      if: always()
      uses: actions/cache/save@v4
      with:
        path: .angular/cache
        key: ${{ runner.os }}-angular-${{ hashFiles('angular.json') }}
