name: 'Cache Node and Composer Modules'
description: 'Cache npm and Composer dependencies'
runs:
  using: 'composite'
  steps:
    - name: Cache npm cache
      uses: actions/cache@v4.2.3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Cache Composer dependencies
      uses: actions/cache@v4.2.3
      with:
        path: |
          ~/.composer/cache
          vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
