name: 'Cache Node Modules'
description: 'Cache npm dependencies'
runs:
  using: 'composite'
  steps:
    - name: Cache Node Modules
      uses: actions/cache@v4.2.3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
