name: 🧹 Lint
permissions:
  contents: read

on: [
  push,
  workflow_call,
  workflow_dispatch
]

jobs:
  lint:
    name: 🧹 Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: 22

      - name: Cache Node Modules
        uses: ./.github/actions/cache-node-modules

      - name: Install Dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint
